# Generated by Django 5.0.3 on 2025-11-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsession',
            name='unattempted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsession',
            name='wrong_count',
            field=models.IntegerField(default=0),
        ),
    ]
